version: "3.7"
services:
  app_proxy:
    restart: always
    environment:
      APP_HOST: Jellyfin
      APP_PORT: 8096
      PROXY_AUTH_ADD: "false"
    container_name: Jellyfin-Proxy
    volumes:
      - /c/umbrel:/shared
  server:
    image: linuxserver/jellyfin:10.11.11@sha256:c123ef2f82195e377d8ca3df275f13f9dfa5c6e61b195958662b42b5e54362ab
    restart: always
    hostname: ${DEVICE_HOSTNAME}
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${UMBREL_ROOT}/home/Downloads:/downloads
      - /c/umbrel:/shared
    ports:
      - 7359:7359/udp
    container_name: Jellyfin
