version: "3.7"
services:
  app_proxy:
    restart: always
    environment:
      APP_HOST: qBittorrent
      APP_PORT: 8080
      PROXY_AUTH_ADD: "true"
      PROXY_AUTH_WHITELIST: /api/*
    container_name: qBittorrent-Proxy
    volumes:
      - /c/umbrel:/shared
  server:
    image: ghcr.io/hotio/qbittorrent:release-5.2.3@sha256:251f7c1561294a9efb5aaafff50adf82952a2975f35dbb2bb519790d5068bcfb
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${UMBREL_ROOT}/home/Downloads:/downloads
      - ${UMBREL_ROOT}/home/Videos/Filmes:/media/Filmes
      - ${UMBREL_ROOT}/home/Videos/Series:/media/Series
      - ${UMBREL_ROOT}/home/Videos/Animes:/media/Animes
      - /c/umbrel:/shared
    restart: always
    container_name: qBittorrent
